// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "139bd6d5-6cf2-44d7-b448-bac1db8c7470";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRelay1Change();
void onRelay2Change();
void onRelay3Change();
void onRelay4Change();

CloudSwitch relay_1;
CloudSwitch relay_2;
CloudSwitch relay_3;
CloudSwitch relay_4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(relay_1, READWRITE, ON_CHANGE, onRelay1Change);
  ArduinoCloud.addProperty(relay_2, READWRITE, ON_CHANGE, onRelay2Change);
  ArduinoCloud.addProperty(relay_3, READWRITE, ON_CHANGE, onRelay3Change);
  ArduinoCloud.addProperty(relay_4, READWRITE, ON_CHANGE, onRelay4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
